import Head from "next/head";
import Hero from "@/components/Hero";

const Page = () => (
  <>
    <Head>
      <title>Budai Akrobatikus Sport Egyesület</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="lg:relative">
      <h1>Ajánlott oldalak</h1>
    </main>
  </>
);
export default Page;
