import { MagnifyingGlassIcon } from "@heroicons/react/20/solid";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Highlighter from "react-highlight-words";

const RECOMMENDED_PAGES = [
  {
    name: "Internationale de Gymnastique",
    href: "https://www.gymnastics.sport/site/",
  },
  {
    name: "Magyar Látványtánc Szövetség",
    href: "https://www.latvanytancok.hu/hu/",
  },
  {
    name: "Magyar Szabadidősport Szövetség",
    href: "https://masport.hu/",
  },
  {
    name: "Magyar Cheer Szövetség",
    href: "https://hungariancheerfederation.hu/",
  },
  {
    name: "Magyar Torna Szövetség",
    href: "https://matsz.hu/",
  },
  {
    name: "ACCADEMIA ACROBATICA SRL",
    href: "https://www.villaggioaccademia.it/en/",
  },
  {
    name: "Érdi Torna Club",
    href: "https://erditornaclub.hu/",
  },
  {
    name: "Puente",
    href: "https://puente.hu/",
  },
  {
    name: "TFSe acro",
    href: "http://tfse.sport.hu/akrobatikus-torna/",
  },
  {
    name: "Pfeifer Ferenc: Az akrobatikus torna Magyarországon.",
    href: "https://mutargy.com/egyeb-mutargy/pfeifer-ferenc-az-akrobatikus-torna-magyarorszagon-a-szerzo-altal-dedikalt-peldany-bp-2010-budaors-epc-ny-szines-kepekkel-es-fotokkal-illusztralt-kiadoi-kartonalt-papirkotes-/",
  },
  {
    name: "Akrobatikus torna A. M. Ignasenko Sport Lap- és Könyvkiadó, 1953",
    href: "https://antikvarium.hu/konyv/a-m-ignasenko-akrobatikus-torna-917149-0?gclid=CjwKCAjwx7GYBhB7EiwA0d8oe-EaAz75af5_9pPDyc9Hw9_jfHZjNJEcYxFCvMMQd1iEW0r1Dghs0BoCOzEQAvD_BwE/",
  },
  {
    name: "Akrobatikus torna - 1958 Garzol Sándor, Kaszper Lászlóné, Szabó Dániel",
    href: "https://www.libri.hu/konyv/Akrobatikus-torna-2.html?ordered&amp;utm_source=hirlevel-system&amp;utm_medium=email&amp;utm_campaign=Vasarlas+visszaigazolasa+-+7987092",
  },
];

const Page = () => {
  const [query, setQuery] = useState("");

  return (
    <>
      <Head>
        <title>Ajánlott oldalak - Budai Akrobatikus Sport Egyesület</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto w-full max-w-7xl pt-8 pb-20 px-4 sm:px-6 space-y-8">
          <h1 className="text-5xl">Ajánlott oldalak</h1>
          <div className="relative rounded-md shadow-sm">
            <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <MagnifyingGlassIcon
                className="h-5 w-5 text-gray-400"
                aria-hidden="true"
              />
            </div>
            <input
              onChange={(e) => setQuery(e.target.value.toLowerCase())}
              type="search"
              className="block w-full rounded-md border-gray-300 pl-10 focus:border-orange-primary focus:ring-orange-primary sm:text-sm"
              placeholder="Keresés..."
            />
          </div>
          <div className="flex flex-col gap-4">
            {RECOMMENDED_PAGES.filter((page) =>
              page.name.toLowerCase().includes(query)
            )
              .sort((a, b) => a.name.localeCompare(b.name))
              .map((page, i) => (
                <Link
                  key={i}
                  href={page.href}
                  className="text-xl bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow after:content-['_↗'] after:text-orange-primary"
                  target="_blank"
                >
                  <Highlighter
                    highlightClassName="bg-yellow-200/70"
                    searchWords={[query]}
                    autoEscape={true}
                    textToHighlight={page.name}
                  />
                </Link>
              ))}
          </div>
        </div>
      </main>
    </>
  );
};
export default Page;
