import { MagnifyingGlassIcon } from "@heroicons/react/20/solid";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Highlighter from "react-highlight-words";

const DOCUMENTS = [
  {
    name: "GDPR - Adatkezelési hozzájárulási nyilatkozat",
    href: "/documents/GDPR%20nyilatkozat.pdf",
  },
  {
    name: "GDPR - Szabályzata",
    href: "/documents/GDPR%20szabalyzat.pdf",
  },
  {
    name: "1 %",
    href: "/documents/2022_adoszam.pdf",
  },
  {
    name: "Házirend",
    href: "/documents/2011hazirend.pdf",
  },
  {
    name: "Alapszabályzat",
    href: "/documents/BASE%20alapszabalyzata.pdf",
  },
  {
    name: "Belépési kérelem",
    href: "/documents/tagfelveteltkerolap.pdf",
  },
  {
    name: "Pártoló tagsági kérelem",
    href: "/documents/partoloitagfelveteltkerolap.pdf",
  },
  {
    name: "Tagnyilvántartó adatlap",
    href: "/documents/tagnyilvantartoadatlap.pdf",
  },
];

const Page = () => {
  const [query, setQuery] = useState("");

  return (
    <>
      <Head>
        <title>Dokumentumok - Budai Akrobatikus Sport Egyesület</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:relative">
        <div className="mx-auto w-full max-w-7xl pt-8 pb-20 px-4 sm:px-6 space-y-8">
          <h1 className="text-5xl">Dokumentumok</h1>
          <div className="relative rounded-md shadow-sm">
            <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <MagnifyingGlassIcon
                className="h-5 w-5 text-gray-400"
                aria-hidden="true"
              />
            </div>
            <input
              onChange={(e) => setQuery(e.target.value.toLowerCase())}
              type="search"
              className="block w-full rounded-md border-gray-300 pl-10 focus:border-orange-primary focus:ring-orange-primary sm:text-sm"
              placeholder="Keresés..."
            />
          </div>
          <div className="flex flex-col gap-4">
            {DOCUMENTS.filter((document) =>
              document.name.toLowerCase().includes(query)
            ).map((document, i) => (
              <Link
                key={i}
                href={document.href}
                className="text-xl bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow after:content-['_↗'] after:text-orange-primary"
                target="_blank"
              >
                <Highlighter
                  highlightClassName="bg-yellow-200/70"
                  searchWords={[query]}
                  autoEscape={true}
                  textToHighlight={document.name}
                />
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};
export default Page;
