import { Dialog, Transition } from "@headlessui/react";
import { PlayIcon } from "@heroicons/react/20/solid";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { Fragment, ReactNode } from "react";

interface IVideos {
  name: ReactNode;
  v: string;
  description?: ReactNode;
}

const VIDEOS: IVideos[] = [
  {
    name: "Junior Akrobatika Vb Katowice Statikus gyakorlatok Sajgál Ágnes-Boros Erika 1989",
    v: "4yYyxGU1ad8",
  },
  {
    name: "Sportakrobatika Hevesi Ált. Iskolában 1989.08.10. (KanizsaTV)",
    v: "sa5HaJtW96U",
  },
  {
    name: "Sportakrobatika Prága Gajcsi R./Kondor A. 1995.06.23. (KanizsaTV)",
    v: "DPVe9oOoH5U",
  },
  {
    name: "Sportakrobatika 2000.11.19. Budapest",
    v: "Rt7vKN-d37c",
  },
  {
    name: "Sportakrobatika 1995.05.24. Riesa",
    v: "AP48M4qX2ok",
  },
  {
    name: "Kossuth Kupa Akrobatika vers, riport/Sajgál,Boros,Váradi",
    v: "lMdv7vos72E",
  },
  {
    name: "2005 XXII. Váradi acro. Nemzetközi akrobatika fesztival Cegléd",
    v: "z8bj0OBsH8M",
  },
  {
    name: "XII.Varadi acro nemzetközi akrobatika fesztival 2005",
    v: "3hSG9bSn2bk",
  },
  {
    name: "Ifjúsági akrobatika ob",
    v: "e9sTXAGtcf8",
    description: (
      <>
        <p className="mt-3 text-base text-gray-500">
          1985 Női páros dinamikus Halmi K-Berla E
        </p>
        <p className="mt-3 text-base text-gray-500">
          Női hármas dinamikus NagyT-Miklós A,Csizmadi
        </p>
        <p className="mt-3 text-base text-gray-500">
          Ffi páros dinamikus. Stadler Zs-Süli B
        </p>
      </>
    ),
  },
  {
    name: "Máté Judith-Bessenyei Kinga hármas Építők (világok harca zene)",
    v: "MvqXy87BxKc",
  },
  {
    name: "Kiszely Krisztina,Boros Erika Négercsók Kupa 1987",
    v: "x-OCFUXNLvA",
  },
  {
    name: (
      <>
        I. Junior Akrobatika Világbajnokság Katowice,Sajgál Ágnes -Boros Erika{" "}
        <br /> összetett 2. hely <br /> 1989 Világ élvonalában a ceglédi
        akrobatika
      </>
    ),
    v: "-6vvjuZl2ek",
  },
  {
    name: "Európa Bajnokság,Világkupa 1989",
    v: "x8xWY8qCjd4",
  },
  {
    name: "Bujáki Barbara-Novák Melinda 1989",
    v: "Dfbo2-HTy58",
  },
  {
    name: "Halmi Katalin-Berla Erika Felnőtt Magyar Bajnokság 2. hely 1985",
    v: "ZCUkSPlgmpo",
  },
];

const Page = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Galéria - Budai Akrobatikus Sport Egyesület</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto w-full max-w-7xl pt-8 pb-20 px-4 sm:px-6 space-y-8">
          <h1 className="text-5xl">Galéria</h1>
          <div className="relative mx-auto max-w-7xl">
            <div className="mx-auto mt-12 grid max-w-lg gap-5 md:grid-cols-2 md:max-w-none lg:grid-cols-3">
              {VIDEOS.map((video) => (
                <Link
                  href={{ query: { v: video.v } }}
                  key={video.v}
                  className="group flex flex-col overflow-hidden rounded-lg shadow-lg"
                >
                  <div className="relative flex-shrink-0">
                    <div className="absolute grid justify-center items-center z-[5] inset-0 bg-opacity-0 group-hover:bg-opacity-50 bg-black group-hover:scale-110 transition-all duration-500">
                      <PlayIcon className="h-16 w-16 fill-transparent group-hover:fill-white transition-all duration-500" />
                    </div>
                    <Image
                      width={480}
                      height={360}
                      className="h-48 w-full object-cover group-hover:scale-110 transition-transform duration-500"
                      src={`/images/youtube_thumbnails/${video.v}.png`}
                      alt={video.name!.toString()}
                    />
                  </div>
                  <div className="flex flex-1 flex-col justify-between bg-white p-6">
                    <div className="flex-1">
                      <span className="mt-2 block">
                        <p className="text-xl font-semibold text-gray-900 group-hover:text-orange-primary">
                          {video.name}
                        </p>
                        {video.description}
                      </span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </main>

      <Transition.Root show={!!router.query.v} as={Fragment}>
        <Dialog
          as="div"
          className="relative z-10"
          onClose={() => router.push({ query: {} })}
        >
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-gray-500 bg-opacity-90 transition-opacity" />
          </Transition.Child>

          <div className="fixed inset-0 z-10 overflow-y-auto">
            <div className="flex min-h-full justify-center p-4 text-center items-center sm:p-0">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                enterTo="opacity-100 translate-y-0 sm:scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 translate-y-0 sm:scale-100"
                leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
              >
                <Dialog.Panel className="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 w-full max-w-5xl sm:p-6">
                  <iframe
                    width="100%"
                    className="aspect-video"
                    src={`https://www.youtube.com/embed/${router.query.v}`}
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                    title={VIDEOS.find(
                      (video) => video.v === router.query.v
                    )?.name?.toString()}
                  />
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition.Root>
    </>
  );
};
export default Page;
